// Generated by CoffeeScript 1.6.3
(function() {
  macgap.window.resize({
    width: 500,
    height: 300
  });

  macgap.window.move({
    x: 500,
    y: 500
  });

  window.onunload = function() {
    return alert('unload');
  };

  window.onload = function() {
    var $bloop;
    $bloop = $('#bloop');
    return $bloop.click(function() {
      return $(this).animate({
        width: (Math.random() * 400) + 100,
        height: (Math.random() * 200) + 100
      });
    });
  };

}).call(this);
